server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://106.14.171.180:3306/spring_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: spring_test
    password: 3zxW2mt6PaZHisnL

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:cn/**/mapper/*.xml